language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t boxdave/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true boxdave/docker-react npm run test